name: "fare-prediction"
services:
  fare-prediction:
    build: ./
    image: fare-prediction:latest
    volumes:
      - .:/code
    tty: true
    stdin_open: true
    command: /bin/bash
    container_name: fare-prediction